FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --timeout=300 --retries=5 mlflow==3.14.0

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", \
     "--backend-store-uri", "sqlite:////mlflow.db", \
     "--default-artifact-root", "/mlflow/artifacts", \
     "--gunicorn-opts", "--forwarded-allow-ips=*"]
