apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: immo
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: immo-streamlit:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: immo-streamlit-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
